name: Test ESP bool parser
on:
  push:
    branches:
      - main
jobs:
  build-python-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.7'

